FROM shinsenter/php:8.3-fpm-nginx

ENV TZ=UTC
ENV WORKERS=1

ENV APP_PATH=/app
ENV DOCUMENT_ROOT=public

ENV DEBUG=0
ENV ENABLE_TUNING_FPM=1
ENV ENABLE_CRONTAB=1
ENV ENABLE_CRONTAB_DEBUG=0
ENV ALLOW_RUNTIME_PHP_ENVVARS=1
ENV DISABLE_AUTORUN_GENERATING_INDEX=1
ENV DISABLE_AUTORUN_COMPOSER_INSTALL=1
ENV DISABLE_GREETING=1

ENV PHP_CURL_CAINFO=/app/cacert.pem
ENV PHP_CURL_CONNECTTIMEOUT=300
ENV PHP_CURL_TIMEOUT=300
ENV PHP_REQUEST_TERMINATE_TIMEOUT=300
ENV PHP_DEFAULT_SOCKET_TIMEOUT=300
ENV PHP_MAX_EXECUTION_TIME=300
ENV PHP_MEMORY_LIMIT=512M

RUN phpaddmod sockets gmp

ADD app/ /app/

ADD docker/supervisor/conf.d/alo.conf /etc/supervisor/conf.d/alo.conf
ADD docker/nginx/00-alo.conf /etc/nginx/custom.d/00-alo.conf
ADD docker/crontab.d/alo /etc/crontab.d/alo
ADD docker/startup/ /startup/